// <auto-generated />
using HangMan.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace HangMan.Data.Migrations
{
    [DbContext(typeof(HangManContext))]
    [Migration("20180316161715_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("HangMan.Models.Hang", b =>
                {
                    b.Property<int>("HangId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("HangMan");

                    b.HasKey("HangId");

                    b.ToTable("Hang");
                });

            modelBuilder.Entity("HangMan.Models.Letters", b =>
                {
                    b.Property<int>("LettersId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Letter");

                    b.HasKey("LettersId");

                    b.ToTable("Letters");
                });

            modelBuilder.Entity("HangMan.Models.Line", b =>
                {
                    b.Property<int>("LineId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Pic");

                    b.HasKey("LineId");

                    b.ToTable("Line");
                });

            modelBuilder.Entity("HangMan.Models.Words", b =>
                {
                    b.Property<int>("WordsId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Word");

                    b.HasKey("WordsId");

                    b.ToTable("Words");
                });
#pragma warning restore 612, 618
        }
    }
}
